name: chatzone
description: "A WhatsApp-like chat application built with Flutter and Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0' # Dart SDK constraint

dependencies: # Add this 'dependencies' block
  flutter:
    sdk: flutter
    # Updated Firebase versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  provider: ^6.1.1
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
